variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'dd08eace-3861-4745-a7e8-89e8a80dc7a1'

  # Agent VM image name
  vmImageName: 'vs2017-win2016'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:

    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: dd08eace-3861-4745-a7e8-89e8a80dc7a1
        resourceGroupName: bsoltisdevopsdemo2